### ISSUE TITLE
Connecting 6x sensors to Teensy 3.6

### ISSUE THREAD

**Issue by akrv** [sparkfun/Qwiic_Magnetometer_MLX90393#2]
with `A0` and `A1` pins, it is possible to address up to 4 sensors.
how can I connect two more sensors?

I quote from the [datasheet](https://cdn.sparkfun.com/assets/e/e/f/2/7/MLX90393-Datasheet-Melexis.PDF)

> I2C_ADDR[6:0] = {EE_I2C_ADDR[4:0],A1,A0} with Ai the user-selectable active-high value of the input pads of the MLX90393, referred to the VDD supply system and EE_I2C_ADDR[4:0] default programmed to 03h, but user accessible for overwrite.

is there a possibility to change the address?
any help would be appreciated?

**Comment by nseidle** [comment]
Hi, Yes it looks like EE_I2C_ADDR[4:0] can be overwritten to accommodate many magnetometers on a single I2C bus.

> I2C_ADDR[6:0] = {EE_I2C_ADDR[4:0],A1,A0} with Ai the user-selectable active-high value of the input pads of the MLX90393, referred to the VDD supply system and EE_I2C_ADDR[4:0] default programmed to 03h, but user accessible for overwrite.

But I can't find the memory location for that register...

[Different datasheet here](http://static6.arrow.com/aropdfconversion/6a2d69f975cb6d54620e77b89738a2edb6eb7eed/2mlx90393-datasheet-melexis.pdf.pdf). 

>I2C_ADDR[6:0] = {EE_I2C_ADDR[4:0],A1,A0} with Ai the user-selectable active-high value of the input pads of the MLX90393, referred to the VDD supply system and EE_I2C_ADDR[4:0] default programmed to 0x03h, but factory accessible for overwrite. 

So unfortunately it's factory writable, not user writable. SparkFun only offers MLX90393xLW-ABA-011-RE but in theory you could do your own board and solder on different MLX90393s. The easier option is to use the [Qwiic Mux](https://www.sparkfun.com/products/14685). 

Hope this helps!
