### ISSUE TITLE
Invalid OSR and DIG_FILT combinations

### ISSUE THREAD

**Issue by tesshellebrekers** [sparkfun/Qwiic_Magnetometer_MLX90393#3]
Hi all,

Thanks for a great library. Just a quick question on the ConfigureSensor example code. According to the datasheet, these combination of OSR and DIG_FILT are not recommended.

OSR = 0; DIG_FILT = 0;
OSR = 1; DIG_FILT = 0;
OSR = 0; DIG_FILT = 1;

The ConfigureSensor example defaults to the first case. Am I understanding this incorrectly? A comment for these invalid combos would be useful for other beginners.

**Comment by nseidle** [comment]
Hi - Unfortunately we don't maintain the library. You should bring this issue up over [here](https://github.com/tedyapo/arduino-MLX90393).
